backend:
  name: github
  repo: bako1/smexnorway
  branch: main # or the branch you want to use for content
media_folder: "src/assets/uploads" # Where images will be uploaded
public_folder: "/assets/uploads" # Path to images after upload

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
